[brew.parser_config]
program_name = "brew"

# ## install
[[brew.sub_commands]]
name = "install"

[[brew.sub_commands.arguments]]
name = "packages"
nargs = "+"

# ## uninstall
[[brew.sub_commands]]
name = "uninstall"

[[brew.sub_commands.arguments]]
name = "packages"
nargs = "+"

# ## update
[[brew.sub_commands]]
name = "update"

# ## upgrade
[[brew.sub_commands]]
name = "upgrade"

# ## search
[[brew.sub_commands]]
name = "search"

[[brew.sub_commands.arguments]]
name = "search_terms"
nargs = "+"

# ## list 子命令
[[brew.sub_commands]]
name = "list"
alias = ["ls"]

[[brew.sub_commands.arguments]]
name = "packages"
nargs = "*"

[[brew.sub_commands.arguments]]
name = "verbose"
opt = ["-v", "--verbose"]
nargs = "0"

# info 子命令
[[brew.sub_commands]]
name = "info"

[[brew.sub_commands.arguments]]
name = "packages"
nargs = "+"

# fetch 子命令（下载源码）
[[brew.sub_commands]]
name = "fetch"

[[brew.sub_commands.arguments]]
name = "packages"
nargs = "+"