# === zypper 操作组 ===

[operations.install]
cmd_format = "zypper install {pkgs}"

[operations.remove]
cmd_format = "zypper remove {pkgs}"

[operations.update_pkg_db]
cmd_format = "zypper refresh"

[operations.upgrade_sys]
cmd_format = "zypper update"

[operations.search_remote]
cmd_format = "zypper search {search_terms}"

[operations.search_local]
cmd_format = "zypper search --installed-only {search_terms}"

[operations.info]
cmd_format = "zypper info {pkgs}"

[operations.list_installed]
cmd_format = "zypper search --installed-only"

[operations.list_files]
cmd_format = "rpm -ql {pkgs}"

[operations.find_file_owner_with_regexp]
cmd_format = "rpm -qf '{regexp}'"

[operations.download_source]
cmd_format = "zypper source-download {pkgs}"